default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost
  port: 5436
development:
  <<: *default
  database: rutube_copiliot

test:
  <<: *default
  database: rutube_copiliot

production:
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: 10
